{% set name = "uassist" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5123fb58c44720464c192f34f46c1501ed6f7d6d795465993014d0d0df911f9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - folium
    - ipyleaflet
    - pyshp
    - exifread
    - python >=3.6

test:
  imports:
    - uassist

about:
  home: https://github.com/nathanmckinney/uassist
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: 'UASsist: Assistant for Unmanned Aircraft System photogrammetry for surveying and mapping applications.'
  doc_url: https://nathanmckinney.github.io/UASsist/
  dev_url: https://github.com/nathanmckinney/uassist

extra:
  recipe-maintainers:
    - nathanmckinney
